development:
  clients:
    default:
      database: touragogo_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: touragogo
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: touragogo_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
