development:
  clients:
    default:
      uri: 'mongodb://localhost:27017/touragogo_development'
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      uri: 'mongodb://localhost:27017/touragogo'
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      uri: 'mongodb://localhost:27017/touragogo_test'
  options:
    raise_not_found_error: false
